### ISSUE TITLE
displayName is missing from API

### ISSUE THREAD

**Issue by amelon** [stampit-org/react-stamp#26]
Hi,

`displayName` is missing from the `reactDesc` `interface` in docs/api.

**Comment by troutowicz** [comment]
Good catch. Want to open a PR?

**Comment by amelon** [comment]
ok I will!

**Comment by amelon** [comment]
you're quicker than me.
I wanted to make a PR but you already did it.
thank you

**Comment by troutowicz** [comment]
You're welcome. :)
