### ISSUE TITLE
Upcoming changes to the standard enable fluent syntax

### ISSUE THREAD

**Issue by koresar** [stampit-org/react-stamp#30]
With the new composables specification the following:
```js
const container = ({
  React,
  Button,
  Text,
}, ...behaviors) => (
  reactStamp(React).compose({
    state: {}
    render(){}
  })
);

const MyComponent = container({
  React,
  Button: button(React),
  Text: text(React),
}, buttonBehavior);
```
can be now improved to
```js
const MyComponent = reactStamp.compose(
  React,
  Button: button(React),
  Text: text(React),
  buttonBehavior,
  {
    state: {},
    render(){}
  });
```
or even
```js
const MyComponent = reactStamp
.compose(React)
.compose({
  Button: button,
  Text: text
})
.compose(buttonBehavior)
.compose({
  state: {},
  render(){}
});
```
Something like that. Up to you actually. :)

@troutowicz what do you think?

**Comment by troutowicz** [comment]
I think I need to play catch up with the spec! I'll come back to this once I do. :)

**Comment by koresar** [comment]
I'll ping you again few days later with implementation example and explanations. :)

**Comment by troutowicz** [comment]
Actually, after looking closer, I don't think either of your examples would work. `React`, `Button`, and `Text` are not stamps. In the container function, `React` is passed to `reactStamp` returning a React stamp. `Button` and `Text` are stateless React components which get referenced in the render method of the HOC produced by the container.

**Comment by koresar** [comment]
Hint: https://github.com/stampit-org/stamp-specification/pull/71

**Comment by troutowicz** [comment]
Yeah, I'm not seeing it. Can you tell me what you expect the result of the below composition to be?

```js
const MyComponent = reactStamp.compose(
  React,
  Button: button(React),
  Text: text(React),
  buttonBehavior,
  {
    state: {},
    render(){}
  });
```
How could `Button` and/or `Text` get referenced inside the `render` method?

**Comment by koresar** [comment]
There is a typo of course. Here it corrected:
```js
const MyComponent = reactStamp.compose(
  React,
  {
    Button: button,
    Text: text,
  },
  buttonBehavior,
  {
    state: {},
    render(){}
  });
```

There are few ways. The simplest one - `React`, `Button`, `Text`, `state` and `render` are all transformed to properties. So `render` can look like this:
```js
render() {
  const {React, state, Button, Text} = this;
  return <Button><Text/></Button>; // something list this...
}
```

The `Button` and `Text` can reference the `React` the same way even though they are HOCs.
```js
const React = {this};
```

**Comment by troutowicz** [comment]
OK, your typo corrections have made a world of difference. :) This gives me some ideas to play with, and has also convinced me that the BDC example in the README is too convoluted.

**Comment by koresar** [comment]
**too** convoluted, mate!

**Comment by troutowicz** [comment]
@koresar see PR #32 and the [bdc](https://github.com/troutowicz/bdc) repo. After simplifying the BDC example, I'm not to sure your suggested improvements are needed anymore. Let me know what you think. :)

**Comment by koresar** [comment]
@troutowicz took a look at the BDC. Didn't understand. Can't find the simplification you're talking about.

**Comment by troutowicz** [comment]
```bash
const Component = reactStamp(React).compose(
  container,
  buttonBehavior
);
```

Container is no longer a factory, just a smart component. I'm not sure I'm understanding why you think the compose method needs an API change.

**Comment by koresar** [comment]
I wouldn't say it's "API change". I'd call it "additional API", more fluent one (probably).

**Comment by troutowicz** [comment]
Going to close this out for now.
