### ISSUE TITLE
remove carret on stamp-utils version

### ISSUE THREAD

**Issue by amelon** [stampit-org/react-stamp#36]
Hello,

i've spent hours to figure out what's wrong with my react project and it appears that react-stamp is incompatible with stamp-utils 1.3.1 (or maybe 1.3.1 has bug)

Actually, with this simple component,

````js
const C = reactStamp(React).compose({
  render() {
    return <div>My react stamp component</div>
  }
})
````
the `compose` method remove `render` because stamp-utils.isDescriptor({ render() {...} }) return true with version 1.3.1 but not with version 1.2.4.

Could you please change carret with tilde on stamp-utils to avoid to use 1.3.1 version ?

````json
  "dependencies": {
    "lodash": "^4.6.1",
    "stamp-utils": "~1.2.4"
  },
````

**Comment by ericelliott** [comment]
Removing the tilde is a good idea, but why not update react-stamp to work with the latest version?

**Comment by amelon** [comment]
Thanks for the quick fix.

**Comment by troutowicz** [comment]
Will push a new release as soon as I can.

**Comment by ericelliott** [comment]
Cool. Thanks. =)
